apiVersion: v1
kind: Pod
metadata:
  name: cent
  labels:
    app: web
spec:
  containers:
    - name: os
      image: centos:7
      command:
        - "sleep"
        - "1000"
      command: ["/bin/bash"]
      args: ["-c","yum install -y httpd;/usr/sbin/httpd && sleep 1000"] 

        
#      command: ["/usr/sbin/httpd"]
  restartPolicy: OnFailure
