apiVersion: v1
kind: Pod
metadata:
  name: ddev
  namespace: dev
spec:
  containers:
    - name: ddev-pod1
      image: ubuntu
      command: 
        - "sleep"
        - "1000"
      resources:
        requests:
          cpu: "250m"
          memory: "250Mi"
        limits:
          cpu: "300m"
          memory: "300Mi" 
