apiVersion: v1
kind: Pod
metadata:
  name: ddev
  namespace: dev
spec:
  containers:
    - name: ddev-pod
      image: ubuntu
      command: 
        - "sleep"
        - "1000"
      resources:
        requests:
          cpu: "150m"
          memory: "250Mi"
        limits:
          cpu: "200m"
          memory: "300Mi" 
