apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  labels:
    type: frontend
spec:
  template:
    metadata:
      name: mypod
      labels:
        type: frontend
    spec:
      containers:
        - name: ngix
          image: nginx:1.7
  replicas: 3
  selector:
    matchLabels:
      type: frontend  
